local shell = require("shell")
shell.execute("wget -f https://raw.githubusercontent.com/DanXvoIsMe/CNet/main/cnet/json.lua /lib/json.lua")
shell.execute("wget -f https://raw.githubusercontent.com/DanXvoIsMe/CNet/main/cnet/cnet.lua /lib/cnet.lua")
shell.execute("wget -f https://raw.githubusercontent.com/DanXvoIsMe/CNet/main/cnet/asciiencryption.lua /lib/asciiencryption.lua")
print("CNet library has been installed!")
